apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-exporter-master
  namespace: kube-system
  annotations:
    k8s-app: node-exporter-master
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: node-exporter-master
      version: v0.17.0
  template:
    metadata:
      labels:
        k8s-app: node-exporter-master
        version: v0.17.0
    spec:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      serviceAccount: node-exporter
      containers:
        - name: prometheus-node-exporter
          image: quay.io/prometheus/node-exporter:v0.17.0
          imagePullPolicy: "IfNotPresent"
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
          resources:
            limits:
              cpu: 10m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
      hostPID: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
      nodeSelector:
        beta.kubernetes.io/os: linux
        node-role.kubernetes.io/master: ""
#      hostNetwork: true

