apiVersion: v1
kind: Service
metadata:
  name: node-exporter-master
  namespace: kube-system
  annotations:
    prometheus.io/scrape: "true"
    k8s-app: "node-exporter"
  labels:
    kubernetes.io/cluster-service: "false"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "NodeExporter"
    k8s-app: "node-exporter"
    node-exporter: "master"
spec:
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    k8s-app: node-exporter-master
