kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-claim
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: prometheus-local-storage
  resources:
    requests:
      storage: 20Gi
