---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: front-end
  namespace: sock-shop
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: front-end

  minReplicas: 1
  maxReplicas: 3

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 35

  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 95
 
