kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-claim
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: grafana-local-storage
  resources:
    requests:
      storage: 0.4Gi
