apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sock-shop-ingress
spec:
  tls:
  - hosts:
    - shop.sock.com
    secretName: sock-shop-secret
  rules:
  - host: shop.sock.com
    http:
      paths:
      - path: /home
        backend:
          serviceName: front-end
          servicePort: 80
